spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
        application:
            name:microservicecloud-config-elane-dev
    
---
spring:
    profiles: test
        application:
            name:microservicecloud-config-elane-test